language: python
python:
  - "3.8"

before_install:
  - pip install pycodestyle

install:
  - pip install -r requirements.txt

script:
  - python -m pytest /tests
  - coverage run -m pytest
  - pyscodestyle --ignore=E722,E501,E402