"""empty message

Revision ID: 8c82240addad
Revises: 4b61d1cc9ac1
Create Date: 2021-04-12 11:42:27.901502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c82240addad'
down_revision = '4b61d1cc9ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'actors', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actors', type_='unique')
    # ### end Alembic commands ###
